// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUh4jh_Qn3qSLH8w_dnOw7aYo8xFgK7Ik',
    appId: '1:295021936433:web:c3e3650452eadd9e04ba10',
    messagingSenderId: '295021936433',
    projectId: 'ejemplo-notificaciones-32ad7',
    authDomain: 'ejemplo-notificaciones-32ad7.firebaseapp.com',
    storageBucket: 'ejemplo-notificaciones-32ad7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNXPxJa0lT9ramI4bPgy5YPqzWZnF7GK4',
    appId: '1:295021936433:android:20e3daab9359f05a04ba10',
    messagingSenderId: '295021936433',
    projectId: 'ejemplo-notificaciones-32ad7',
    storageBucket: 'ejemplo-notificaciones-32ad7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyOWQ21M-LrAxvD87-TMhEitoKC7s4Z8I',
    appId: '1:295021936433:ios:af8b55a9d104cf2c04ba10',
    messagingSenderId: '295021936433',
    projectId: 'ejemplo-notificaciones-32ad7',
    storageBucket: 'ejemplo-notificaciones-32ad7.appspot.com',
    iosClientId: '295021936433-bcddhhbdpkedmo80kje9051oj6d66bsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.phone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyOWQ21M-LrAxvD87-TMhEitoKC7s4Z8I',
    appId: '1:295021936433:ios:af8b55a9d104cf2c04ba10',
    messagingSenderId: '295021936433',
    projectId: 'ejemplo-notificaciones-32ad7',
    storageBucket: 'ejemplo-notificaciones-32ad7.appspot.com',
    iosClientId: '295021936433-bcddhhbdpkedmo80kje9051oj6d66bsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.phone',
  );
}
